version: "2"
services:
    api:
        build: .
        ports:
            - "8300:8000"
        links:
            - pg
        volumes:
            - .:/usr/src/app
        command: python -m http.server 6000
        depends_on:
            - pg
        environment:
            - DATABASE_URL=postgres://user:dbpass@pg/db
            - DEBUG=False
            - DATABASE_URL_TEST=postgres://user:dbpass@pg/test
            - DEBUG=True
            - PORT=8000

    pg:
        image: postgres:9.6.2
        ports:
            - "10432:5432"
        expose:
            - "5432"
        environment:
            - POSTGRES_PASSWORD=dbpass
            - POSTGRES_USER=user
            - POSTGRES_DB=db
